---
- name: Create /var/docker/rancher directory
  ansible.builtin.file:
    dest: /var/docker/rancher
    state: directory
    mode: 0755

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /var/docker/rancher/docker-compose.yml
    mode: 0640

- name: Start the Rancher containers
  community.docker.docker_compose_v2:
    project_src: /var/docker/rancher
    state: present
    pull: always
    build: always
    recreate: always

- name: Wait for 10 seconds
  ansible.builtin.wait_for:
        timeout: 10

- name: Generate API token
  ansible.builtin.uri:
    url: "{{ rancher_url }}/v3-public/localProviders/local?action=login"
    method: POST
    body: "{{ lookup('ansible.builtin.template','token.j2') }}"
    status_code: 201
    body_format: json